-- Give `daily_login_claim` a surrogate primary key, for consistency with every other
-- model in the schema, while keeping `(user_id, claimed_on)` as the natural key.
--
-- The composite key moves from `@@id` to `@@unique`, so the "one reward per day"
-- rule is unchanged — only *which* constraint is the primary key changes. Cost: one
-- additional index (`daily_login_claims_pkey` on `id`) alongside the unique index.
--
-- Hand-written rather than generated: the generated DDL adds `id` as `NOT NULL`,
-- which fails on any table that has rows.

-- ── 1. New column, nullable so existing rows can be backfilled ──────────────
ALTER TABLE "daily_login_claims"
  ADD COLUMN "id" TEXT;

-- ── 2. Backfill ─────────────────────────────────────────────────────────────
-- Existing rows get a UUID rather than a cuid, since cuids are generated by Prisma
-- and not available in SQL. `id` is an opaque surrogate, so the format difference is
-- cosmetic; new rows get a cuid from `@default(cuid())`.
-- (gen_random_uuid() is core since PostgreSQL 13; this server is 18.6.)
UPDATE "daily_login_claims"
SET "id" = gen_random_uuid()::text
WHERE "id" IS NULL;

-- ── 3. Abort rather than leaving an unkeyed row ─────────────────────────────
DO $$
DECLARE missing INTEGER;
BEGIN
  SELECT count(*) INTO missing
  FROM "daily_login_claims"
  WHERE "id" IS NULL OR "id" = '';

  IF missing > 0 THEN
    RAISE EXCEPTION
      '% daily_login_claim row(s) could not be assigned a surrogate id. Aborting.',
      missing;
  END IF;
END $$;

-- ── 4. Swap the key ─────────────────────────────────────────────────────────
-- PK moves to the surrogate; the natural key stays, as a unique index. The old PK
-- already guaranteed (user_id, claimed_on) uniqueness, so creating this index cannot
-- fail on existing data.
ALTER TABLE "daily_login_claims"
  DROP CONSTRAINT IF EXISTS "daily_login_claims_pkey";

ALTER TABLE "daily_login_claims"
  ALTER COLUMN "id" SET NOT NULL,
  ADD CONSTRAINT "daily_login_claims_pkey" PRIMARY KEY ("id");

CREATE UNIQUE INDEX "daily_login_claims_user_id_claimed_on_key"
  ON "daily_login_claims"("user_id", "claimed_on");
